### 25개 지역구로 통합하기

In [1]:
import pandas as pd
import requests
import json
from tqdm import tqdm
import warnings
warnings.filterwarnings(action='ignore') 

# from IPython.core.interactiveshell import InteractiveShell
# InteractiveShell.ast_node_interactivity = "all"

In [2]:
import os

os.chdir(r'C:\Users\USER\Desktop\데이터\제출용데이터모음')

In [17]:
score_df_bus_station = pd.read_pickle('./bus_coord2address.pickle')
score_df_bus_station.head()

,정류장번호,정류장명,위도,경도,정보수집일시,모바일단축번호,도시코드,도시명,관리도시명,coord2address,region_2depth_name
0,ASB285000077,성환8리,36.921468,127.122774,20221012050123,77.0,34040,아산시,아산,"{'road_address': None, 'address': {'address_na...",천안시 서북구
1,ASB285000078,송덕,36.923783,127.118976,20221012050123,78.0,34040,아산시,아산,"{'road_address': None, 'address': {'address_na...",천안시 서북구
2,ASB285000079,국립축산과학원,36.925931,127.111136,20221012050123,79.0,34040,아산시,아산,"{'road_address': None, 'address': {'address_na...",천안시 서북구
3,ASB285000094,성환8리,36.921479,127.122505,20221012050123,94.0,34040,아산시,아산,"{'road_address': None, 'address': {'address_na...",천안시 서북구
4,ASB285000095,성환터미널,36.917221,127.132732,20221012050123,95.0,34040,아산시,아산,"{'road_address': None, 'address': {'address_na...",천안시 서북구

In [18]:
score_df_bus_station['읍/면/동'] = score_df_bus_station['coord2address'].apply(lambda elm : elm.get('address').get('address_name').split()[3])
score_df_bus_station.head()

,정류장번호,정류장명,위도,경도,정보수집일시,모바일단축번호,도시코드,도시명,관리도시명,coord2address,region_2depth_name,읍/면/동
0,ASB285000077,성환8리,36.921468,127.122774,20221012050123,77.0,34040,아산시,아산,"{'road_address': None, 'address': {'address_na...",천안시 서북구,성환읍
1,ASB285000078,송덕,36.923783,127.118976,20221012050123,78.0,34040,아산시,아산,"{'road_address': None, 'address': {'address_na...",천안시 서북구,성환읍
2,ASB285000079,국립축산과학원,36.925931,127.111136,20221012050123,79.0,34040,아산시,아산,"{'road_address': None, 'address': {'address_na...",천안시 서북구,성환읍
3,ASB285000094,성환8리,36.921479,127.122505,20221012050123,94.0,34040,아산시,아산,"{'road_address': None, 'address': {'address_na...",천안시 서북구,성환읍
4,ASB285000095,성환터미널,36.917221,127.132732,20221012050123,95.0,34040,아산시,아산,"{'road_address': None, 'address': {'address_na...",천안시 서북구,성환읍

In [19]:
score_df_bus_station = score_df_bus_station['읍/면/동'].value_counts()
score_df_bus_station

성환읍    248
목천읍    157
광덕면    142
입장면    131
성거읍    126
병천면    114
불당동    108
직산읍    107
풍세면    102
성남면     97
북면      94
쌍용동     81
성정동     78
동면      73
백석동     65
수신면     60
신부동     51
신방동     49
두정동     44
안서동     33
봉명동     30
성성동     27
청당동     27
구성동     25
원성동     23
다가동     22
용곡동     22
차암동     21
유량동     21
신당동     21
삼룡동     19
업성동     19
청수동     17
영성동     11
대흥동     10
사직동     10
구룡동      8
문화동      7
성황동      6
부대동      3
오룡동      3
와촌동      2
Name: 읍/면/동, dtype: int64

천안시의 읍/면/동의 40개 지역을 25개 지역으로 분류 합니다.

In [4]:
score_df_bus_station_cp = score_df_bus_station.copy()
score_df_bus_station_cp['대분류'] = None
score_df_bus_station_cp2 =score_df_bus_station_cp.copy()
target ='차암동'
clf_1 = '부성동'
score_df_bus_station_cp.loc[score_df_bus_station_cp['읍/면/동']==target,'대분류']=clf_1
score_df_bus_station_cp[score_df_bus_station_cp['읍/면/동']==target]
score_df_bus_station_cp2['대분류'] = score_df_bus_station_cp2['대분류'].fillna(score_df_bus_station_cp2['읍/면/동'])

score_df_bus_station_cp2[score_df_bus_station_cp2['대분류']=='풍세면']

,정류장번호,정류장명,위도,경도,MT1,CS2,PS3,SC4,AC5,PK6,...,category_sum,공원거리구분_A,공원거리구분_B,CH거리구분_A,CH거리구분_B,하천거리구분_A,하천거리구분_B,score,읍/면/동,대분류
143,ASB288000927,삼태리 종점,36.736221,127.084408,0,0,0,0,0,0,...,0,0,0,2,3,0,0,7,풍세면,풍세면
144,ASB288000928,삼태리 종점,36.736280,127.084587,0,0,0,0,0,0,...,0,0,0,2,3,0,0,7,풍세면,풍세면
145,ASB288000931,세교1리,36.759166,127.109270,0,0,0,0,0,0,...,1,0,0,1,1,0,0,4,풍세면,풍세면
146,ASB288000935,원당,36.736982,127.089511,0,0,0,0,0,0,...,0,0,1,3,25,0,0,32,풍세면,풍세면
147,ASB288000936,삼태리/원당,36.737086,127.089483,0,0,0,0,0,0,...,0,0,1,3,24,0,0,31,풍세면,풍세면
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2169,CAB285071676,우신주택,36.724576,127.119358,0,1,1,1,1,1,...,9,0,0,4,11,0,0,28,풍세면,풍세면
2272,GGB277103981,남풍세TG(경유),36.719733,127.140533,0,0,0,0,0,0,...,0,0,0,5,2,0,0,12,풍세면,풍세면
2273,GGB277103982,남풍세TG(경유),36.719683,127.140833,0,0,0,0,0,0,...,0,0,0,4,3,0,0,11,풍세면,풍세면
2274,GGB277103997,남풍세IC(경유),36.723283,127.141617,0,0,0,0,0,0,...,0,0,0,4,3,0,0,11,풍세면,풍세면
2275,GGB277103998,남풍세IC(경유),36.722800,127.141200,0,0,0,0,0,0,...,0,0,0,4,3,0,0,11,풍세면,풍세면

In [ ]:
# 40 개에서 -> 25개로 분류된 지역의 데이터 셋을 저장
# score_df_bus_station_cp2.to_pickle('./최종사용데이터_25개구.pickle')